apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Values.microservices.data-service.serviceName}}'
  labels:
    app: '{{.Values.microservices.data-service.serviceName}}'
spec:
  replicas: '{{.Values.microservices.data-service.avgReplicas}}'
  selector:
    matchLabels:
      app: '{{.Values.microservices.data-service.serviceName}}'
  template:
    metadata:
      labels:
        app: '{{.Values.microservices.data-service.serviceName}}'
    spec:
      containers:
      - name: '{{.Values.microservices.data-service.serviceName}}'
        image: '{{.Values.microservices.data-service.dockerImage}}'
        ports:
        - containerPort: '{{.Values.microservices.data-service.containerPort}}'
        env:
        - name: '{{.Values.microservices.data-serviceenvs.MYSQL_ROOT_PASSWORD.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.data-service.serviceName}}'
              key: '{{.Values.microservices.data-serviceenvs.MYSQL_ROOT_PASSWORD.name}}'
        - name: '{{.Values.microservices.data-serviceenvs.MYSQL_DATABASE.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.data-service.serviceName}}'
              key: '{{.Values.microservices.data-serviceenvs.MYSQL_DATABASE.name}}'
        - name: '{{.Values.microservices.data-serviceenvs.DB_HOST.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.data-service.serviceName}}'
              key: '{{.Values.microservices.data-serviceenvs.DB_HOST.name}}'
        - name: '{{.Values.microservices.data-serviceenvs.DB_USERNAME.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.data-service.serviceName}}'
              key: '{{.Values.microservices.data-serviceenvs.DB_USERNAME.name}}'
        - name: '{{.Values.microservices.data-serviceenvs.DB_PASSWORD.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.data-service.serviceName}}'
              key: '{{.Values.microservices.data-serviceenvs.DB_PASSWORD.name}}'
