apiVersion: v1
kind: Service
metadata:
  name: '{{.Values.microservices.data-service.serviceName}}'
spec:
  selector:
    app: '{{.Values.microservices.data-service.serviceName}}-mysql'
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ""
